# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphscope/proto/query_args.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!graphscope/proto/query_args.proto\x12\x06gs.rpc\x1a\x19google/protobuf/any.proto\"/\n\tQueryArgs\x12\"\n\x04\x61rgs\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')



_QUERYARGS = DESCRIPTOR.message_types_by_name['QueryArgs']
QueryArgs = _reflection.GeneratedProtocolMessageType('QueryArgs', (_message.Message,), {
  'DESCRIPTOR' : _QUERYARGS,
  '__module__' : 'graphscope.proto.query_args_pb2'
  # @@protoc_insertion_point(class_scope:gs.rpc.QueryArgs)
  })
_sym_db.RegisterMessage(QueryArgs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYARGS._serialized_start=72
  _QUERYARGS._serialized_end=119
# @@protoc_insertion_point(module_scope)
