apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ _name or 'nginx-example' }}
  {% if _namespace -%}
  namespace: {{ _namespace }}
  {%- endif %}
  labels:
    app: {{ _name or 'nginx-example' }}
spec:
  selector:
    matchLabels:
      app: {{ _name or 'nginx-example' }}
  template:
    metadata:
      labels:
        app: {{ _name or 'nginx-example' }}
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: {{ _name or 'nginx-example' }}
        image: {{ _image or 'nginx' }}
        resources:
          limits:
            memory: 50Mi
            cpu: 100m
          requests:
            memory: 50Mi
            cpu: 100m
        volumeMounts: []
        #- name: varlog
        #  mountPath: /var/log
        #- name: varlibdockercontainers
        #  mountPath: /var/lib/docker/containers
        #  readOnly: true
      terminationGracePeriodSeconds: 30
      volumes: []
      #- name: varlog
      #  hostPath:
      #    path: /var/log
      #- name: varlibdockercontainers
      #  hostPath:
      #    path: /var/lib/docker/containers