[tool.poetry]
name = "gds-template-pack"
version = "0.1.1"
description = "A GOV.UK design system template pack for Django Pattern Library."
authors = ["Ben Dickinson <ben.dickinson@torchbox.com>"]
keywords = ["Django", "django-pattern-library", "GDS"]
readme = "README.md"

packages = [
    { include = "gds_template_pack" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
django-pattern-library = "^0.5"

[build-system]
requires = ["poetry>=1.1.12,<2"]
build-backend = "poetry.core.masonry.api"
