[tool.poetry]
name = "pathsearch"
version = "1.1.4"
description = "A script to search for a file in a list of directories."
authors = ["mrlegohead0x45 <mrlegohead0x45@gmail.com>"]
license = "MIT"
homepage = "https://github.com/mrlegohead0x45/pathsearch"
repository = "https://github.com/mrlegohead0x45/pathsearch"
readme = "README.rst"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Environment :: Console"
    # poetry adds license and python version
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
mypy = "^0.942"
flake8 = "^4.0.1"
pre-commit = "^2.18.1"
pytest = "^7.1.1"

[tool.poetry.scripts]
pathsearch = "pathsearch:real_main"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
