[tool.pytest.ini_options]
addopts = "--cov=agoradesk_py"
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.poetry]
name = "agoradesk_py"
version = "0.3.1"
description = "Python Interface for Agoradesk.com and LocalMonero.co API"
authors = ["marvin8 <marvin8@tuta.io>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
homepage = "https://codeberg.org/MarvinsCryptoTools/agoradesk_py"
repository = "https://codeberg.org/MarvinsCryptoTools/agoradesk_py"
classifiers = [
    "Programming Language :: Python",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Intended Audience :: Developers",
    "Topic :: Office/Business :: Financial"
]

[tool.poetry.urls]
"Changelog" = "https://codeberg.org/MarvinsCryptoTools/agoradesk_py/src/branch/main/CHANGELOG.md"
"Bug Tracker" = "https://codeberg.org/MarvinsCryptoTools/agoradesk_py/issues"


[tool.poetry.dependencies]
python = "^3.8"
arrow = "^1.2.1"
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
pylint = "^2.12.2"
flake8 = "^4.0.1"
black = "^22.1.0"
dlint = "^0.12.0"
flake8-eradicate = "^1.2.0"
mypy = "^0.950"
pytest-testmon = "^1.3.1"
pytest-cov = "^3.0.0"
pytest = "^7.0.1"
pytest-mock = "^3.7.0"
flake8-bugbear = "^22.1.11"
pep8-naming = "^0.12.1"
flake8-black = "^0.3.2"
flake8-import-order = "^0.18.1"
bandit = "^1.7.4"
safety = "^1.10.3"
flake8-annotations = "^2.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
