[tool.poetry]
name = "writeprints-static"
version = "0.0.2"
description = "Extract lexical and syntactic features for authorship attribution research."
authors = ["writeprints-static Authors"]
readme = "README.md"
license = "ISC"
repository = "https://github.com/literary-materials/writeprints-static"

[tool.poetry.dependencies]
python = "^3.8"
spacy = "3.0.8"
scipy = "^1.5.0"
numpy = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
mkdocs = "^1.3.0"

[build-system]
requires = ["poetry>=1.1.11"]
build-backend = "poetry.masonry.api"
