[tool.poetry]
name = "crossplain"
version = "0.6.0"
description = "Small layer on top of crossplane that uses plain Python objects instead of dicts. Includes intuitive ways to modify the config."
authors = ["Ewen Le Bihan <hey@ewen.works>"]
license = "MIT"
repository = "https://github.com/ewen-lbh/crossplain"
readme = "README.md"
homepage = "https://ewen.works/crossplain"

[tool.poetry.dependencies]
python = "^3.10"
crossplane = "^0.5.7"

[tool.poetry.dev-dependencies]
rich = "^12.0.0"
ward = "^0.66.0-beta.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
