[tool.poetry]
name = "webpipe"
version = "0.0.0"
description = "webpipe"
authors = ["Nikhil Rao <nikhil@webpipe.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
