[tool.poetry]
name = "ast_monitor"
version = "0.1.3"
description = "AST-Monitor is a wearable Raspberry Pi computer for cyclists"
authors = ["Iztok Fister Jr. <iztok@iztok-jr-fister.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
PyQt5 = "*"
matplotlib = "*"
geopy = "*"
pyqt-feedback-flow = "*"
tcxreader = "*"
sport-activities-features = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
