log_level = "debug"

[http]
host = "127.0.0.1"
port = 8080
api_tokens = []

[irc.server]
host = "irc.server.example"
port = 6667
ssl = false
password = "secret"
rate_limit = 0.5

[irc.bot]
nickname = "Weitersager"
realname = "Weitersager"

[irc]
commands = [
  "MODE Weitersager +i",
]

[[irc.channels]]
name = "#party"

[[irc.channels]]
name = "#secretlab"
password = "555-secret"
