[project]
name = "molliesim"
description = "Simulator of the Mollie API for testing purposes."
readme = "README.md"
dependencies = [
  'pydantic ~= 1.9',
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
]
requires-python = ">=3.5"
dynamic = ["version"]

[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"


[tool.pytest.ini_options]
pythonpath = [
  "src"
]
