[tool.poetry]
name = "py_package"
version = "0.1.0"
description = ""
authors = ["Felix Zhao <felix@arcanum.ai>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
