[tool.poetry]
name = "dictones"
version = "0.1.1"
description = "Little bit better than dict"
authors = ["to101 <to101kv@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
