
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-08T21:48:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "20272f8f543d8285be64bae16484bf6289e60922",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
