[tool.poetry]
name = "niolithic"
version = "0.1.0"
description = "A simple Matrix client library wrapped around `matrix-nio`"
license = "MIT"
readme = "README.md"
authors = ["Maximillian Strand <maximillian.strand@protonmail.com>"]
homepage = "https://gitlab.com/deepadmax/niolithic"

[tool.poetry.dependencies]
python = "^3.10"
matrix-nio = {extras = ["e2e"], version = "^0.19.0"}
rich = "^12.3.0"
Markdown = "^3.3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
