base_model_cpu: "https://zenodo.org/record/6327742/files/MitoNet_v1_base_cpu.pth?download=1"
render_model_cpu: "https://zenodo.org/record/6327742/files/MitoNet_v1_render_cpu.pth?download=1"

base_model_gpu: "https://zenodo.org/record/6327742/files/MitoNet_v1_base_gpu.pth?download=1"
render_model_gpu: "https://zenodo.org/record/6327742/files/MitoNet_v1_render_gpu.pth?download=1"

class_names:
- mito

labels:
- 1

norms:
  mean: 0.57287007
  std: 0.12740536

padding_factor: 16

thing_list:
- 1
