[tool.poetry]
name = "jessiql"
version = "1.0.0-rc1"
description = ""
authors = ["Mark Vartanyan <kolypto@gmail.com>"]
repository = 'https://github.com/kolypto/py-jessiql'
include = ["jessiql/py.typed"]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = {version = "~1.3.7;~1.4.14", extras = ["mypy"]}
fastapi = {version = ">=0.51", optional = true}
graphql-core = {version = ">=3.0.0", optional = true}

[tool.poetry.dev-dependencies]
nox = ">=2020.8.22"
pytest = ">=6.0.1"
pytest-cov = ">=2.10.1"
psycopg2 = ">=2.8.6"
pydantic = ">=1.6.0"
fastapi = ">=0.51.0"
requests = ">=2.25.1"
graphql-core = ">=3.1.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
testpaths = [
    "tests/",
]

# all markers: $ pytest --markers
markers = [
    'extra: optional tests (mypy, etc)'
]
