[project]
name = "Rh-s-PyTool"
version = "0.0.3"
description = "Instruments used in school-project"
authors = [
    { name = "skahanium", email = "skahanium@gmail.com" },
]
readme = "README.md"
dependencies = [
    "numpy>=1.22.3",
    "Rh-s-PyTool>=0.0.1",
]
requires-python = ">=3.10"

[project.license]
text = "MIT"

[project.urls]
Github = "https://github.com/skahanium/Rh-s-PyTool"
Documentation = "https://skahanium.notion.site/Rh-s-PyTool-bf7ab98fba544187b2132c613f0835ea"

[tool.pdm]

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
