
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T17:21:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2bfecbb2b13ed58fa8cd209b09e2ebd60625d66",
 "version": "v4.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
