[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]

[[tool.mypy.overrides]]
module = "css_parser"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "enlighten"
ignore_missing_imports = true
