
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-08T23:29:05-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "471e7ed5411dca702b290a30206a793274439841",
 "version": "0.25.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
