
# Derived in part from https://github.com/google/brotli-wheels
#
# Copyright (c) 2009, 2010, 2013-2016 by the Brotli Authors.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


name: Run tests and build wheel and sdist on all supported OS and Python

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
      name: Build source distribution
      runs-on: ubuntu-20.04

      steps:
          - uses: actions/checkout@v2

          - name: Checkout and install reqs
            run: |
                pip install --upgrade --user build twine pip setuptools

          - name: Build sdist
            run: |
                python setup.py sdist bdist_wheel
                twine check dist/*

          - name: Collect built sdist
            uses: actions/upload-artifact@v2
            with:
                path: dist/*.tar.gz

    test_on_many_oses:
        name: Run tests ${{ matrix.python }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        defaults:
          run:
            shell: bash

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-20.04, macos-11, windows-2022]
                python: ["3.6", "3.7", "3.8", "3.9", "3.10"]

        steps:
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "${{ matrix.python }}"

            - uses: actions/checkout@v2

            - name: Install
              run: pip install -e . -r requirements-dev.txt

            - name: Run tests
              run: pytest -vvs boolean
