from typing import Any

EFI_BOOT_SERVICES_64_BIT: Any
EFI_RUNTIME_SERVICES_64_BIT: Any
EFI_SMM_SYSTEM_TABLE2_64_BIT: Any
BS_PROTOCOLS: Any
BS_PROTOCOLS_INFO_64_BIT: Any
OFFSET_TO_SERVICE: Any
EFI_PEI_SERVICES_32_BIT: Any
