apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{_name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{_crn or 'view'}}
subjects:
- kind: ServiceAccount
  name: {{_sa}}
  {% if _namespace -%}
  namespace: {{ _namespace }}
  {%- endif %}