[build-system]
requires = ["setuptools >= 42", "versioningit ~= 1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "atomate2"
description = "atomate2 is a library of materials science workflows"
readme = "README.md"
keywords = ["high-throughput", "automated", "workflow", "dft", "vasp"]
license = {text = "modified BSD"}
authors = [{name = "Alex Ganose", email = "alexganose@gmail.com"}]
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",
    "Operating System :: OS Independent",
    "Topic :: Other/Nonlisted Topic",
    "Topic :: Scientific/Engineering",
]
requires-python = '>="3.8"'
dependencies = [
    'pymatgen>=2022.3.22',
    'custodian>=2019.8.24',
    "pydantic",
    "monty",
    'jobflow>=0.1.5',
    "PyYAML",
    "numpy",
    "click",
]

[project.optional-dependencies]
amset = ["amset>=0.4.15", "pydash"]
cclib = ["cclib"]
phonons = ["phonopy>=1.10.8"]
docs = [
    "numpydoc==1.3.1",
    "mistune==0.8.4",
    "ipython==8.3.0",
    "FireWorks==2.0.3",
    "autodoc_pydantic==1.6.2",
    "jupyter-book==0.12.3",
]
dev = ["pre-commit>=2.12.1"]
tests = [
    "pytest==7.1.2",
    "pytest-cov==3.0.0",
    "FireWorks==2.0.3",
]
strict = [
    "pydantic==1.9.0",
    "pymatgen==2022.4.26",
    "custodian==2022.2.13",
    "monty==2022.4.26",
    "jobflow==0.1.8",
    "click==8.1.3",
    "PyYAML==6.0",
    "cclib==1.7.1",
    "numpy",
]

[project.scripts]
atm = "atomate2.cli:cli"

[project.urls]
homepage = "https://materialsproject.github.io/atomate2/"
repository = "https://github.com/hackingmaterials/atomate2"
documentation = "https://materialsproject.github.io/atomate2/"
changelog = "https://github.com/hackingmaterials/atomate2/blob/main/docs/about/changelog.md"

[tool.setuptools.package-data]
atomate2 = ["py.typed"]
"atomate2.vasp.sets" = ["*.yaml"]
"atomate2.vasp.schemas.calc_types" = ["*.yaml"]

[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.1"

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
max-doc-length = 88
select = "C, E, F, W, B, B950"
extend-ignore = "E203, W503, E501, F401, RST21"
min-python-version = "3.8.0"
docstring-convention = "numpy"
rst-roles = "class, func, ref, obj"

[tool.mypy]
ignore_missing_imports = true
no_strict_optional = true

[tool.coverage.run]
include = ["src/*"]
parallel = true
branch = true

[tool.coverage.paths]
source = ["src/"]

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_lines = [
    '^\s*assert False(,|$)',
    'if typing.TYPE_CHECKING:',
    '^\s*@overload( |$)',
]
