
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-05T15:35:18+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffd3bc4d95d25cdecaff66c7070e1e3e5d01bce8",
 "version": "1.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
