
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T13:04:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f67d91aff5b4eeeda06887c0004c40e46ac9ce9d",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
