
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-08T23:12:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3925f49f99c730ccd9c6f196729fbb4c423234ac",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
