
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-07T18:21:36+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e550ae408128b24db9ac72d915c6df4928d64a30",
 "version": "0.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
