[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bus-cli"
version = "0.0.0"
description = "Bus, the ultimate configuration manager."
readme = "README.md"
license = { file = "LICENSE.md" }
authors = [
    { name = "Jordan Jimenez", email = "jordanjimenez510@gmail.com" },
    { name = "Luciano Remes", email = "cybergenik@gmail.com" },
    { name = "Yifei Sun", email = "yifei@email.com" },
]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.7"
dependencies = [
]

[project.urls]
Repository = "https://github.com/bus-sh/bus-cli"

[project.scripts]
bus-cli = "cli.main:main"
