
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-05T17:28:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3cdbf2c85a74c9e043c898595efe71aa92291d4",
 "version": "0.0.79.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
