[tool.poetry]
name = "pls"
description = "`pls` is a prettier and powerful `ls` for the pros."
version = "4.0.3"

authors = ["Dhruv Bhanushali"]

license = "GPL-3.0-or-later"
readme = "README.md"

homepage = "https://dhruvkb.github.io/pls"
repository = "https://github.com/dhruvkb/pls"
documentation = "https://dhruvkb.github.io/pls"

[tool.poetry.scripts]
pls = "pls.main:main"
pls-dev = "pls.main:dev"

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^6.0"
rich = "^12.0.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
ipython = "^8.0.1"
pytest = "^7.0.0"
pytest-lazy-fixture = "^0.6.3"
freezegun = "^1.1.0"
jsonschema = "^4.4.0"
requests = "^2.27.1"
pytest-cov = "^3.0.0"

[tool.pytest.ini_options]
cache_dir = ".pytest_cache"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
