[tool.poetry]
name = "gitops-kubernetes"
version = "0.1.1"
description = "Implementa GitOps com Kubernetes"
authors = ["E5R Development Team"]
maintainers = ["Erlimar Silva Campos <erlimar@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/e5r/gitops-kubernetes"
repository = "https://github.com/e5r/gitops-kubernetes"
documentation = "https://github.com/e5r/gitops-kubernetes"
keywords = ["git", "kubernetes", "gitops", "devops", "e5r"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: Portuguese (Brazilian)",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Clustering",
    "Topic :: System :: Distributed Computing",
    "Topic :: System :: Installation/Setup",
    "Topic :: System :: Software Distribution",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
tomli = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
