[tool.poetry]
name = "huey-stubs"
version = "0.0.2"
license = "Apache-2.0"
description = "Type stubs for huey"
authors = ["Henrik Bruådal <henrik.bruasdal@gmail.com>"]
readme = "README.md"
repository = "https://github.com/henribru/huey-stubs"
packages = [
    { include = "huey-stubs" },
]
classifiers = [
    "Typing :: Stubs Only",
]

[tool.poetry.dependencies]
python = "^3.4"
huey = "^2.4.3"
typing-extensions = ">3.10.0,<5.0.0"
typing = {version = "^3.10.0", python = "<3.5"}

[tool.poetry.dev-dependencies]
black = {version = "^22.3.0", python = "^3.9"}
isort = {version = "^5.10.1", python = "^3.9"}
mypy = {version = "^0.950", python = "^3.9"}
typed-ast = {version = "^1.5.3", python = "^3.9"}

[tool.isort]
profile = "black"
known_first_party = "huey"
combine_as_imports = true


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
