
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-01T14:49:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9d18b785fbb31a8076313018b0c66daed0615af",
 "version": "1.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
