[tool.poetry]
name = "redshift_client"
version = "0.7.0"
description = "Redshift client-SDK"
authors = ["Product Team <development@fluidattacks.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Deprecated = "^1.2.12"
psycopg2 = "^2.8.6"
fa-purity = "^1.5.0"
types-Deprecated = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
