[tool.poetry]
authors = ["Didier SCHMITT <dschmitt@equancy.com>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
description = "Datalake Catalog"
license = "MIT"
name = "datalake-catalog"
readme = "README.md"
repository = "https://github.com/equancy/datalake-catalog"
version = "1.0.3"

[tool.poetry.dependencies]
Flask = "^2.0.2"
Flask-JWT-Extended = "^4.3.1"
PyMySQL = "^1.0.2"
click = "^8.0.3"
gunicorn = "^20.1.0"
jsonschema = "^4.2.1"
pony = "^0.7.14"
psycopg2-binary = "^2.9.3"
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
coverage = "^6.0.1"
flake9 = "^3.8.3"
pytest = "^6.2.5"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flake8]
ignore = "E501,W503"

[tool.black]
line-length = 125
target-version = ["py38"]

[tool.coverage.report]
omit = ["tests/*"]

[tool.poetry.scripts]
catalog = "datalake_catalog.main:cli"

[tool.pytest.ini_options]
addopts = "-ra -v --no-header"
markers = [
  "backends: marks tests requiring a backend database engines",
]
minversion = "6.0"
testpaths = ["tests"]
