ALLOWED_CONFIG_FILES = ['yml', 'yaml']
ALL_SERVICES = "All"

AWS_RESOURCE_VPC = "VPC"
AWS_RESOURCE_ECS = "ECS"
AWS_RESOURCE_RDS = "RDS"
AWS_RESOURCE_ELB = "ELB"
AWS_RESOURCE_R53 = "R53"

ALLOWED_AWS_RESOURCES = [AWS_RESOURCE_VPC,
                         AWS_RESOURCE_ECS, AWS_RESOURCE_RDS, AWS_RESOURCE_ELB, AWS_RESOURCE_R53]
ALL_RESOURCE_DELETE = [AWS_RESOURCE_ECS,
                       AWS_RESOURCE_ELB, AWS_RESOURCE_R53, AWS_RESOURCE_RDS, ALL_SERVICES]

AWS_RESOURCE_TYPE_VPC = "ec2"
AWS_RESOURCE_TYPE_EC2 = "ec2"
AWS_RESOURCE_TYPE_ECR = "ecr"
AWS_RESOURCE_TYPE_ECS = "ecs"
AWS_RESOURCE_TYPE_RDS = "rds"
AWS_RESOURCE_TYPE_ELB = "elbv2"
AWS_RESOURCE_TYPE_R53 = "route53"

BOTO_CLIENT_NAMES = [AWS_RESOURCE_TYPE_VPC, AWS_RESOURCE_TYPE_ECR,
                     AWS_RESOURCE_TYPE_ECS, AWS_RESOURCE_TYPE_RDS, AWS_RESOURCE_TYPE_ELB, AWS_RESOURCE_TYPE_R53]

VPC_CIDR_BLOCK_1 = "10.1.0.0/16"
VPC_CIDR_BLOCK_2 = "10.2.0.0/16"
AWS_CLUSTER_NAME = "sg-sample-cluster"
AWS_TASK_NAME = "sg-sample-task"  # need to make a combination
REPOSITORY_NAME = "dev"  # code value will go here
IMAGE_TAG = "develop"   # imagetag will go here
AWS_SERVICE_NAME = "content"    # context value will go here
AWS_CPU = "512"  # cpu will go here
AWS_MEMORY = "1024"  # memory will go here
DESIRED_COUNT = 1  # desiredcount will go here
AWS_RDS_ENGINE = "postgres"
AWS_RDS_USERNAME = "admin123"
AWS_RDS_PASSWORD = "admin123"
