# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ondewo.t2s import custom_phonemizer_pb2 as ondewo_dot_t2s_dot_custom__phonemizer__pb2


class CustomPhonemizersStub(object):
    """endpoints of custom phonemizer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomPhonemizer = channel.unary_unary(
                '/ondewo.t2s.CustomPhonemizers/GetCustomPhonemizer',
                request_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.SerializeToString,
                response_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.CustomPhonemizerProto.FromString,
                )
        self.CreateCustomPhonemizer = channel.unary_unary(
                '/ondewo.t2s.CustomPhonemizers/CreateCustomPhonemizer',
                request_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.CreateCustomPhonemizerRequest.SerializeToString,
                response_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.FromString,
                )
        self.DeleteCustomPhonemizer = channel.unary_unary(
                '/ondewo.t2s.CustomPhonemizers/DeleteCustomPhonemizer',
                request_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateCustomPhonemizer = channel.unary_unary(
                '/ondewo.t2s.CustomPhonemizers/UpdateCustomPhonemizer',
                request_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.UpdateCustomPhonemizerRequest.SerializeToString,
                response_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.CustomPhonemizerProto.FromString,
                )
        self.ListCustomPhonemizer = channel.unary_unary(
                '/ondewo.t2s.CustomPhonemizers/ListCustomPhonemizer',
                request_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.ListCustomPhonemizerRequest.SerializeToString,
                response_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.ListCustomPhonemizerResponse.FromString,
                )


class CustomPhonemizersServicer(object):
    """endpoints of custom phonemizer
    """

    def GetCustomPhonemizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomPhonemizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomPhonemizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomPhonemizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomPhonemizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomPhonemizersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomPhonemizer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomPhonemizer,
                    request_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.FromString,
                    response_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.CustomPhonemizerProto.SerializeToString,
            ),
            'CreateCustomPhonemizer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomPhonemizer,
                    request_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.CreateCustomPhonemizerRequest.FromString,
                    response_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.SerializeToString,
            ),
            'DeleteCustomPhonemizer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomPhonemizer,
                    request_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateCustomPhonemizer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomPhonemizer,
                    request_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.UpdateCustomPhonemizerRequest.FromString,
                    response_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.CustomPhonemizerProto.SerializeToString,
            ),
            'ListCustomPhonemizer': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomPhonemizer,
                    request_deserializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.ListCustomPhonemizerRequest.FromString,
                    response_serializer=ondewo_dot_t2s_dot_custom__phonemizer__pb2.ListCustomPhonemizerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ondewo.t2s.CustomPhonemizers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomPhonemizers(object):
    """endpoints of custom phonemizer
    """

    @staticmethod
    def GetCustomPhonemizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.t2s.CustomPhonemizers/GetCustomPhonemizer',
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.SerializeToString,
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.CustomPhonemizerProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCustomPhonemizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.t2s.CustomPhonemizers/CreateCustomPhonemizer',
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.CreateCustomPhonemizerRequest.SerializeToString,
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCustomPhonemizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.t2s.CustomPhonemizers/DeleteCustomPhonemizer',
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.PhonemizerId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCustomPhonemizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.t2s.CustomPhonemizers/UpdateCustomPhonemizer',
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.UpdateCustomPhonemizerRequest.SerializeToString,
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.CustomPhonemizerProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCustomPhonemizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.t2s.CustomPhonemizers/ListCustomPhonemizer',
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.ListCustomPhonemizerRequest.SerializeToString,
            ondewo_dot_t2s_dot_custom__phonemizer__pb2.ListCustomPhonemizerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
