[tool.poetry]
name = "theory-ai"
version = "0.0.1"
description = "Cloud native machine learning primitives"
authors = ["Sole Ahab <old.ocean.creature@gmail.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
simple-parsing = "^0.0.19"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
