pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and:
        - "check-success=build (docs)"
        - "check-success=build (pep8)"
        - "check-success=build (pkglint)"
        - "check-success=build (3.8)"
        - "check-success=build (3.9)"
        - "check-success=build (3.10)"
        - "-draft"
        - or:
          - "approved-reviews-by=dhellmann"
          - "author=dhellmann"
    actions:
      merge:
        method: merge
