
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-06T17:53:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d66db9b2a8f274632564bc9f2b26f0ab33f43902",
 "version": "0.2.0.post0.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
