
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-04T09:28:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "85309628effe4f6bc9141301832999c6fdab089f",
 "version": "3.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
