[tool.black]
line-length = 100
skip-string-normalization = true
target_version = [
    "py37",
    "py38",
    "py39",
    "py310",
]

[tool.jupyter-releaser]
skip = ["check-links"]

[tool.check-manifest]
ignore = [".mailmap", "*.yml", "*.yaml"]

[tool.tbump.version]
current = "7.3.1"
regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
  ((?P<channel>a|b|rc|.dev)(?P<release>\d+))?
'''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "jupyter_client/_version.py"

[tool.pytest.ini_options]
addopts = "-raXs --durations 10 --color=yes --doctest-modules"
testpaths = [
    "jupyter_client/tests/"
]
timeout = 300
# Restore this setting to debug failures
# timeout_method = "thread"
asyncio_mode = "auto"
filterwarnings= [
  # Fail on warnings
  "error",

  # We need to handle properly closing loops as part of https://github.com/jupyter/jupyter_client/issues/755.
  "ignore:unclosed <socket.socket:ResourceWarning",
  "ignore:unclosed event loop:ResourceWarning",

  # Workaround for https://github.com/tornadoweb/tornado/issues/3106
  # (To be fixed in Tornado 6.2)
  "ignore:There is no current event loop:DeprecationWarning:tornado",

  # ZMQ uses Future internally, which raises a DeprecationWarning
  # When there is no loop running.
  # We could eventually find a way to make sure these are only created
  # when there is a running event loop.
  "ignore:There is no current event loop:DeprecationWarning:zmq",
]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
no_implicit_reexport = false
pretty = true
show_error_context = true
show_error_codes = true
strict_equality = true
strict_optional = true
warn_unused_configs = true
warn_redundant_casts = true
warn_return_any = false
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
    "traitlets.*",
    "jupyter_core.*",
    "ipykernel",
    "entrypoints"
]
ignore_missing_imports = true
