
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-02T03:47:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "42122541c1b2dfd779cb2ee4be13c7bea1fa1318",
 "version": "1.16.0.post.dev454"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
