
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-02T17:18:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9091a987513beb9b9474280030858a2a04c34788",
 "version": "0.0.78.post0.dev59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
