[dependencies]
fxhash = "0.2.1"
itertools = "0.10.3"
ordered-float = "2.10.0"

[dependencies.graphbench]
path = "local_dependencies/graphbench"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.16.1"

[lib]
crate-type = ["cdylib"]
name = "platypus"

[package]
edition = "2021"
name = "platypus-graph"
version = "0.1.1"
