[build-system]
requires = [
    "setuptools >= 40.6.0",
    "wheel",
    "Cython",
    "numpy"
]
backend="setuptools.build_meta"

[tool.cibuildwheel.macos]
archs = ["auto", "universal2"]
# test-skip = ["*universal2:arm64"]

