language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
      global:
        # Doctr deploy key for griffin-h/lightcurve_fitting
        - secure: "LLnsCBvO1Oma2BmBRHS+wl2R4lBkvVfrKdwAjplzSZpnX1HQSveQozW7y0mmG2T5WB5R7CknxFA9jkdDBbUsP84U7BSWHm+PRR2U86IPgrthZkT0BxEMaYrHOD+A+694cMq2/YwylhgjZGq5HqnDzEI7wSgjpdwdxzqmcG/ZzTu70KFy+yV07m1gPxo6Ck0okOiDFYDyfhfhcclGU+PTEcf1tMhIDUQO/FtVVHAaKYZC2anfiRgmY5qMjZAo9xKBqdedsw8oVQAxkTdH3BVPO0fLW02+7wMkMBB3G3Ta1l4/o5AzFY+kPEa3wBURSlypnGOrCdoloKBIE+/8GMO0A8Nt3m6AzLUTbPO3Yc34X8Yibvt4LLZ35ZNOgLq90b6wswm17ngOh63eL8B+5iu08eFe+tbvDlFqaYctnYWLxD7Qphld3ZXB+l97pD5l1c0G1fhfxacHorX03OhYeQs1/ngiLS1QOa45pn1/E7clOSsXZMHSQDHy95oRfKXf9Km74OvMca9fJtdK9L1kOz2M0yqcm9JuJdIuLLMlyoojFwFxFB3AQ0k0RQSwDf349ZIpInkuKqy8vIvo2iKojTgawM8i22CDMP5/gZsgwr6MUpw7jUvueJ1HuaKwIGi9f6E2yYZwXqRpYp/OXV7CrTMPBqnOjBf1ReldqelHGdc/xIk="

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - set -e  # If any of the following steps fail, just stop at that point.
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .  # Publish the documentation.

branches:
  only:
    - master
