[tool.black]
    target-version = ['py38']
    experimental-string-processing = true
    skip-magic-trailing-comma = true

[tool.coverage.run]
    branch = true
    omit = [
        "setup.py",
        "data_browser/migrations/*.py",
    ]
    source = [
        "data_browser",
        "tests",
    ]
    parallel = true

[tool.coverage.report]
    exclude_lines = [
        "assert False",
        "pragma: no cover",
        "pragma: django 3.1.3",
    ]
    show_missing = true
    skip_covered = true
    skip_empty = true

[tool.flake8]
    extend-ignore = "E203"
    max-line-length = 88

[tool.isort]
    multi_line_output=3
    include_trailing_comma=true
    force_grid_wrap=0
    use_parentheses=true
    line_length=88
    default_section="THIRDPARTY"
    known_first_party="data_browser,tests"

[tool.pytest.ini_options]
    addopts = [
        "-ra",
        "--reuse-db",
        "--durations=20",
    ]
    norecursedirs = [
        ".*",
        "__pycache__",
        "static",
        "fixtures",
        "templates",
        "migrations",
        "frontend",
        "build",
        "*.egg-info",
        "dist",
        "web_root",
    ]
