
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T18:09:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "410ec0bb8454ec923e2c2b0b0c6fe1ae570e48c2",
 "version": "0.0.78.post0.dev68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
