
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-02T10:09:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea63cbc9b8d0757a5df243a936bace5e34a38bfc",
 "version": "2.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
