
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-02T04:08:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "81cceba5a91ad7390656840f4adf8c98182676d8",
 "version": "1.16.0.post.dev457"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
