
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-05T19:10:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c94c6b754ed0d065a02fd7d178f165ccecff4e29",
 "version": "v4.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
