[tool.poetry]
name = "pytrms"
version = "0.1.0"
description = "Python bundle for proton-transfer reaction mass-spectrometry (PTR-MS).\u001b[D\u001b[D\u001b["
authors = ["Moritz Koenemann <moritz.k-man@arcor.de>"]
license = "GPL-2.0"

[tool.poetry.dependencies]
python = "^3.5"
h5py = "^3.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
