# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk_metric_pb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sdk_metric_pb.proto',
  package='com.tencent.monitor.sdk_metric_pb.pb',
  syntax='proto3',
  serialized_options=b'Z\002pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13sdk_metric_pb.proto\x12$com.tencent.monitor.sdk_metric_pb.pb\"\x8c\x01\n\nMetricList\x12\r\n\x05\x61ppId\x18\x01 \x01(\r\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x1d\n\x15reportRegionWithAgent\x18\x03 \x01(\t\x12=\n\x07metrics\x18\x04 \x03(\x0b\x32,.com.tencent.monitor.sdk_metric_pb.pb.Metric\"\xa2\x03\n\x06Metric\x12\r\n\x05\x61ppId\x18\x01 \x01(\r\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x13\n\x0bmeasurement\x18\x04 \x01(\t\x12\x37\n\x04tags\x18\x05 \x03(\x0b\x32).com.tencent.monitor.sdk_metric_pb.pb.Tag\x12@\n\x06\x66ields\x18\x06 \x03(\x0b\x32\x30.com.tencent.monitor.sdk_metric_pb.pb.BasicField\x12L\n\x0ehistogramField\x18\x07 \x03(\x0b\x32\x34.com.tencent.monitor.sdk_metric_pb.pb.HistogramField\x12H\n\x0csummaryField\x18\x08 \x03(\x0b\x32\x32.com.tencent.monitor.sdk_metric_pb.pb.SummaryField\x12@\n\x08hllField\x18\t \x03(\x0b\x32..com.tencent.monitor.sdk_metric_pb.pb.HllField\"!\n\x03Tag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"m\n\nBasicField\x12\x42\n\tfieldType\x18\x01 \x01(\x0e\x32/.com.tencent.monitor.sdk_metric_pb.pb.FieldType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\"=\n\x0eHistogramField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0e\n\x06\x62ucket\x18\x03 \x03(\x01\"=\n\x0cSummaryField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x10\n\x08quantile\x18\x03 \x03(\x01\":\n\x08HllField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\tprecision\x18\x03 \x01(\x04*S\n\tFieldType\x12\x07\n\x03SUM\x10\x00\x12\x07\n\x03MAX\x10\x01\x12\x07\n\x03MIN\x10\x02\x12\t\n\x05\x46IRST\x10\x03\x12\x08\n\x04LAST\x10\x04\x12\x0b\n\x07\x43OUNTER\x10\x05\x12\t\n\x05GAUGE\x10\x06\x42\x04Z\x02pbb\x06proto3'
)

_FIELDTYPE = _descriptor.EnumDescriptor(
  name='FieldType',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.FieldType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUM', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAX', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FIRST', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAST', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNTER', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAUGE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=957,
  serialized_end=1040,
)
_sym_db.RegisterEnumDescriptor(_FIELDTYPE)

FieldType = enum_type_wrapper.EnumTypeWrapper(_FIELDTYPE)
SUM = 0
MAX = 1
MIN = 2
FIRST = 3
LAST = 4
COUNTER = 5
GAUGE = 6



_METRICLIST = _descriptor.Descriptor(
  name='MetricList',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.MetricList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appId', full_name='com.tencent.monitor.sdk_metric_pb.pb.MetricList.appId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='com.tencent.monitor.sdk_metric_pb.pb.MetricList.namespace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reportRegionWithAgent', full_name='com.tencent.monitor.sdk_metric_pb.pb.MetricList.reportRegionWithAgent', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='com.tencent.monitor.sdk_metric_pb.pb.MetricList.metrics', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=202,
)


_METRIC = _descriptor.Descriptor(
  name='Metric',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appId', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.appId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.namespace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurement', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.measurement', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.tags', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fields', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.fields', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='histogramField', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.histogramField', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summaryField', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.summaryField', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hllField', full_name='com.tencent.monitor.sdk_metric_pb.pb.Metric.hllField', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=623,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.tencent.monitor.sdk_metric_pb.pb.Tag.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.monitor.sdk_metric_pb.pb.Tag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=658,
)


_BASICFIELD = _descriptor.Descriptor(
  name='BasicField',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.BasicField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fieldType', full_name='com.tencent.monitor.sdk_metric_pb.pb.BasicField.fieldType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.tencent.monitor.sdk_metric_pb.pb.BasicField.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.monitor.sdk_metric_pb.pb.BasicField.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=769,
)


_HISTOGRAMFIELD = _descriptor.Descriptor(
  name='HistogramField',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.HistogramField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.tencent.monitor.sdk_metric_pb.pb.HistogramField.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.monitor.sdk_metric_pb.pb.HistogramField.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bucket', full_name='com.tencent.monitor.sdk_metric_pb.pb.HistogramField.bucket', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=771,
  serialized_end=832,
)


_SUMMARYFIELD = _descriptor.Descriptor(
  name='SummaryField',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.SummaryField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.tencent.monitor.sdk_metric_pb.pb.SummaryField.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.monitor.sdk_metric_pb.pb.SummaryField.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantile', full_name='com.tencent.monitor.sdk_metric_pb.pb.SummaryField.quantile', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=834,
  serialized_end=895,
)


_HLLFIELD = _descriptor.Descriptor(
  name='HllField',
  full_name='com.tencent.monitor.sdk_metric_pb.pb.HllField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.tencent.monitor.sdk_metric_pb.pb.HllField.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.tencent.monitor.sdk_metric_pb.pb.HllField.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='precision', full_name='com.tencent.monitor.sdk_metric_pb.pb.HllField.precision', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=897,
  serialized_end=955,
)

_METRICLIST.fields_by_name['metrics'].message_type = _METRIC
_METRIC.fields_by_name['tags'].message_type = _TAG
_METRIC.fields_by_name['fields'].message_type = _BASICFIELD
_METRIC.fields_by_name['histogramField'].message_type = _HISTOGRAMFIELD
_METRIC.fields_by_name['summaryField'].message_type = _SUMMARYFIELD
_METRIC.fields_by_name['hllField'].message_type = _HLLFIELD
_BASICFIELD.fields_by_name['fieldType'].enum_type = _FIELDTYPE
DESCRIPTOR.message_types_by_name['MetricList'] = _METRICLIST
DESCRIPTOR.message_types_by_name['Metric'] = _METRIC
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['BasicField'] = _BASICFIELD
DESCRIPTOR.message_types_by_name['HistogramField'] = _HISTOGRAMFIELD
DESCRIPTOR.message_types_by_name['SummaryField'] = _SUMMARYFIELD
DESCRIPTOR.message_types_by_name['HllField'] = _HLLFIELD
DESCRIPTOR.enum_types_by_name['FieldType'] = _FIELDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricList = _reflection.GeneratedProtocolMessageType('MetricList', (_message.Message,), {
  'DESCRIPTOR' : _METRICLIST,
  '__module__' : 'sdk_metric_pb_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.monitor.sdk_metric_pb.pb.MetricList)
  })
_sym_db.RegisterMessage(MetricList)

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), {
  'DESCRIPTOR' : _METRIC,
  '__module__' : 'sdk_metric_pb_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.monitor.sdk_metric_pb.pb.Metric)
  })
_sym_db.RegisterMessage(Metric)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), {
  'DESCRIPTOR' : _TAG,
  '__module__' : 'sdk_metric_pb_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.monitor.sdk_metric_pb.pb.Tag)
  })
_sym_db.RegisterMessage(Tag)

BasicField = _reflection.GeneratedProtocolMessageType('BasicField', (_message.Message,), {
  'DESCRIPTOR' : _BASICFIELD,
  '__module__' : 'sdk_metric_pb_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.monitor.sdk_metric_pb.pb.BasicField)
  })
_sym_db.RegisterMessage(BasicField)

HistogramField = _reflection.GeneratedProtocolMessageType('HistogramField', (_message.Message,), {
  'DESCRIPTOR' : _HISTOGRAMFIELD,
  '__module__' : 'sdk_metric_pb_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.monitor.sdk_metric_pb.pb.HistogramField)
  })
_sym_db.RegisterMessage(HistogramField)

SummaryField = _reflection.GeneratedProtocolMessageType('SummaryField', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYFIELD,
  '__module__' : 'sdk_metric_pb_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.monitor.sdk_metric_pb.pb.SummaryField)
  })
_sym_db.RegisterMessage(SummaryField)

HllField = _reflection.GeneratedProtocolMessageType('HllField', (_message.Message,), {
  'DESCRIPTOR' : _HLLFIELD,
  '__module__' : 'sdk_metric_pb_pb2'
  # @@protoc_insertion_point(class_scope:com.tencent.monitor.sdk_metric_pb.pb.HllField)
  })
_sym_db.RegisterMessage(HllField)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
