# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: continual/rpc/rpc/error_details.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%continual/rpc/rpc/error_details.proto\x12\x11\x63ontinual.rpc.rpc\"}\n\x0c\x45rrorDetails\x12=\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32,.continual.rpc.rpc.ErrorDetails.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x38Z6github.com/continualiq/continual/continual/rpc/rpc;rpcb\x06proto3')



_ERRORDETAILS = DESCRIPTOR.message_types_by_name['ErrorDetails']
_ERRORDETAILS_DETAILSENTRY = _ERRORDETAILS.nested_types_by_name['DetailsEntry']
ErrorDetails = _reflection.GeneratedProtocolMessageType('ErrorDetails', (_message.Message,), {

  'DetailsEntry' : _reflection.GeneratedProtocolMessageType('DetailsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ERRORDETAILS_DETAILSENTRY,
    '__module__' : 'continual.rpc.rpc.error_details_pb2'
    # @@protoc_insertion_point(class_scope:continual.rpc.rpc.ErrorDetails.DetailsEntry)
    })
  ,
  'DESCRIPTOR' : _ERRORDETAILS,
  '__module__' : 'continual.rpc.rpc.error_details_pb2'
  # @@protoc_insertion_point(class_scope:continual.rpc.rpc.ErrorDetails)
  })
_sym_db.RegisterMessage(ErrorDetails)
_sym_db.RegisterMessage(ErrorDetails.DetailsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/continualiq/continual/continual/rpc/rpc;rpc'
  _ERRORDETAILS_DETAILSENTRY._options = None
  _ERRORDETAILS_DETAILSENTRY._serialized_options = b'8\001'
  _ERRORDETAILS._serialized_start=60
  _ERRORDETAILS._serialized_end=185
  _ERRORDETAILS_DETAILSENTRY._serialized_start=139
  _ERRORDETAILS_DETAILSENTRY._serialized_end=185
# @@protoc_insertion_point(module_scope)
