
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T10:57:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5adc55ae8c5baf0ff4c92fd90d18ddc4e7855d3",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
