
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-04T19:41:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "04290262d963a262c20179cc3c31be42acbccc41",
 "version": "0.0.78.post0.dev80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
