# Generated by Django 3.2.4 on 2021-07-05 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210705_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
