# Generated by Django 3.2.4 on 2021-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_parent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
