# Generated by Django 3.2.4 on 2021-07-05 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
