# Generated by Django 3.2.4 on 2021-07-13 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_parent_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='school.school')),
            ],
        ),
    ]
