# Generated by Django 3.2.4 on 2021-07-13 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
