[tool.poetry]
name = "dj-static-revision"
version = "0.5"
description = "Revision info for Django static file"
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/AgriConnect/dj-static-revision.git"
homepage = "https://github.com/AgriConnect/dj-static-revision"
readme = "README.rst"
keywords = ["django", "static", "version", "cache"]
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Environment :: Web Environment",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
dulwich = "^0.19.15"
single-version = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-flake8 = "^1.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
