[tool.poetry]
name = "einenlum-weather-project"
version = "0.0.2"
description = "A dummy project to get the current temperature"
authors = ["Yann Rabiller <yann.rabiller@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only"
]
packages = [
    { include = 'weather' }
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
