[tool.poetry]
name = "callue"
version = "1.0.0"
description = "A webserver preprocessor of sorts"
authors = ["Callum <callum@jcwyt.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
numpy = "^1.22.2"
bottle = "^0.12.19"
Paste = "^3.5.0"
rcssmin = "^1.1.0"
htmlmin = "^0.1.12"
jsmin = "^3.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"