url:
  #开发环境
  dev: http://xxx.xxx.xx.xx:xxxx
  #测试环境
  test: http://xxx.xxx.xx.xx:xxxx
  #预发布环境
  staging: http://xxx.xxx.xx.xx:xxxx
  #生产环境
  prod: http://xxx.xxx.xx.xx:xxxx

cookie:

token:
