[tool.poetry]
name = "from-jupyter"
version = "0.1.0"
authors = ["Antonio Feregrino <antonio.feregrino@gmail.com>"]
description = "Blogging from Jupyter notebooks"
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/fferegrino/from-jupyter"
repository = "https://github.com/fferegrino/from-jupyter"

[tool.poetry.scripts]
from-jupyter = "from_jupyter.__main__:cli"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
