[tool.poetry]
name = "chilitools"
version = "0.1.16"
description = "A collection of tools for working with the CHILI publish REST API"
authors = ["Austin <austin.meier@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
Pillow = "^9.1.0"
coloredlogs = "^15.0.1"
img2pdf = "^0.4.4"
pyperclip = "^1.8.2"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
