[tool.poetry]
name = "dou_verify"
version = "0.1.0"
description = ""
authors = ["satoru <satorulogic@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyquery = "^1.4.3"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
ipython = "^8.3.0"
black = {version = "^22.3.0", allow-prereleases = true}
pytest-mock = "^3.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
