[tool.poetry]
name = "fmricat"
version = "0.0.1"
description = "An automated fMRI analysis toolbox"
authors = ["seven <yusaiwen@mail.bnu.edu.cn>"]

[tool.poetry.dependencies]
python = "3.10.2" 
scipy = "1.8.0"
numpy = "^1.22.3"
rich = "^12.4.0"
click = "^8.1.3"
nilearn = "^0.9.1"
nipype = "^1.6.9"
PyYAML = "^6.0"
pybids = "^0.15.1"
termcolor = "^1.1.0"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
denoiser = "fmricat.denoiser:main()"
