cluster: "ebio-cluster/jobsubmit"
cluster-config: "ebio-cluster/cluster.yml"
cluster-status: "ebio-cluster/jobstatus"
jobscript: "ebio-cluster/jobscript.sh"
jobs: 100
#immediate-submit: true
verbose: false
#notemp: true
use-conda: true
conda-frontend: mamba
rerun-incomplete: true
keep-going: true
nolock: true
max-jobs-per-second: 5
max-status-checks-per-second: 1
latency-wait: 60
local-cores: 1
restart-times: 3
scheduler: greedy
printshellcmds: true
