[tool.poetry]
name = "tickytacky"
version = "0.9.0"
description = "Tickytacky pixel game maker"
readme = "README.md"
authors = ["JP Etcheber <jetcheber@gmail.com>"]
license = "GNU General Public License"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pyglet = "^1.5.23"
Flask = "^2.1.2"
Pillow = "^9.1.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pyflakes = "^2.4.0"
pycodestyle = "^2.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
