[tool.poetry]
name = "bbpb"
version = "0.0.1"
description = "Library for working with protobuf messages without a protobuf type definition."
authors = ["Ryan Winkelmaier <ryan.winkelmaier@nccgroup.com>"]
license = "MIT"
repository = "https://github.com/nccgroup/blackboxprotobuf"
keywords = ["protobuf"]
packages = [
    { include = "blackboxprotobuf" }
]
