[tool.poetry]
name = "py-attire-schema"
version = "1.1.0"
description = "Base logging schema used by attire logger projects"
authors = ["jamesgeraghty"]
repository = 'https://github.com/SecurityRiskAdvisors/py-attire-schema'
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
