[tool.poetry]
name = "pytorch-imbalance-loss"
version = "0.0.1"
description = "Imbalance Losses in PyTorch for NLP"
authors = ["Chenghao Mou <mouchenghao@gmail.com>"]
license = "Apache License, Version 2.0"

[tool.poetry.dependencies]
python = "^3.8"
torch = "<=1.9.0"
einops = "^0.3.2"
torchtyping = "^0.1.4"
typeguard = "^2.13.3"
numpy = "^1.22.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
