[tool.poetry]
name = "RideSims"
version = "0.1.0"
description = "For running automated ride sequences for RideSims."
authors = ["copev313 <copev313@gmail.com>"]
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Topic :: Software Development :: Version Control :: Git",
]
license = "MIT"

[tool.poetry.scripts]
ridesims = "ridesims.cli_app:app"

[tool.poetry.dependencies]
python = "^3.10"
PyDirectInput = "^1.0.4"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.10.1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
