
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-06T10:06:46+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4829c98fe26b07d1bb589dbc04e4198b235bdc1",
 "version": "0.27.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
