[tool.poetry]
name = "sw_ops_common"
version = "0.0.1"
description = ""
authors = ["xuxygo"]

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
PyMySQL = "^1.0.2"
DBUtils = "3.0.2"
PyYAML = "^5.4.1"
redis = "^4.2.2"
aiomysql = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
