
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T20:23:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0feda346aaa077a0c967594110bcfe3d4c1c74ce",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
