
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T11:01:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec548d975d2a39b2f69e96648dc5fa4965405fc2",
 "version": "3.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
