[tool]

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

versioning = "semver"

# git tag template for releases
tag = "v."


[tool.poetry]
name = "xepmts"
version = "0.5.9"
homepage = "https://github.com/jmosbacher/xepmts"
documentation = "https://xepmts.readthedocs.io/"
description = "Python client for accessing the XENON experiment PMT data."
authors = ["Yossi Mosbacher <joe.mosbacher@gmail.com>"]
readme = "README.rst"
license =  "MIT"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
packages = [
    { include = "xepmts" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.scripts]
xepmts = "xepmts.cli:main"


[tool.poetry.dependencies]
python = ">=3.8,<3.11"
click = "*"
eve-panel = "^0.3.27"
xeauth = "^0.1.19"
toml = "^0.10.2"
streamz = "*"
xepmts-endpoints = "^0.1.4"

hvplot = {version = "^0.7.0", optional = true}
dask = {extras = ["dataframe"], version = "^2021.2.0", optional = true}


[tool.poetry.extras]
dask = ["dask[dataframe]"]
plotting = ["hvplot"]
live = ["streamz"]
full = ["dask", "hvplot", "streamz",
         "ipywidgets_bokeh",
         "ipywidgets"]

[tool.poetry.dev-dependencies]
bumpversion = "*"
coverage = "*"
flake8 = "*"
invoke = "*"
isort = "*"
pylint = "*"
pytest = "*"
sphinx = "*"
tox = "*"
yapf = "*"
nbsphinx = "*"
sphinx-material = "*"
numpydoc = "*"
ipykernel = "*"
jupyter = "*"
pyviz_comms = "*"

[build-system]
requires = ["poetry-core>=1.0.8", "setuptools"]
build-backend = "poetry.core.masonry.api"
