[tool.poetry]
name = "file-io-cli-tddschn"
version = "0.1.1"
description = "Command-line tool to upload files to https://file.io"
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tddschn/file.io-cli-tddschn"
repository = "https://github.com/tddschn/file.io-cli-tddschn"
classifiers = [
	"Topic :: Utilities"
]
keywords = ["file.io", "cli", "upload", "download"]

[tool.poetry.scripts]
"file.io-cli" = "file_io_cli_tddschn.file_io_cli:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/file.io-cli-tddschn/issues"

[tool.poetry.dependencies]
python = "^3.10"
clipboard = "^0.0.4"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
toml = "^0.10.2"
yapf = "^0.32.0"
better-exceptions = "^0.3.3"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
