[tool.poetry]
name = "minder.research_portal_client"
version = "0.1.3"
description = ""
authors = ["UK DRI Care Research & Technology centre"]
readme = "README.md"
packages = [
    { include = "minder" },
    { include = "minder/research_portal_client/py.typed" },
]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = {extras = ["speedups"], version = "^3.8.1"}
backoff = "^1.11.1"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
coverage = {extras = ["toml"], version = "^6.3.2"}
flake8 = "^4.0.1"
flake8-bugbear = "^22.3.23"
mypy = "^0.942"
black = "^22.3.0"
types-python-dateutil = "^2.8.10"
backoff-stubs = "^1.11.1"

[tool.pytest.ini_options]
python_files = "tests/test_*.py"

[tool.coverage.run]
omit = [".*", "tests/*", "*/site-packages/*"]

[tool.black]
line-length=120

[tool.mypy]
namespace_packages=true
explicit_package_bases=true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
