[tool]
[tool.poetry]
authors = ["Filip Brzek <filip.brzek@gmail.com>"]
classifiers = [
  'Development Status :: 2 - Pre-Alpha',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: MIT License',
  'Natural Language :: English',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.6',
  'Programming Language :: Python :: 3.7',
  'Programming Language :: Python :: 3.8',
  'Programming Language :: Python :: 3.9',
]
description = "Simulates the loan installments at different interest rates."
homepage = "https://github.com/PhillCli/wibor-simulation"
license = "MIT"
name = "wibor-simulation"
packages = [
  {include = "wibor_simulation"},
  {include = "tests", format = "sdist"},
]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
fire = "0.4.0"
python = ">=3.6.1,<4.0"

black = {version = "20.8b1", optional = true}
flake8 = {version = "3.8.4", optional = true}
flake8-docstrings = {version = "^1.6.0", optional = true}
isort = {version = "5.6.4", optional = true}
mkdocs = {version = "^1.1.2", optional = true}
mkdocs-autorefs = {version = "0.1.1", optional = true}
mkdocs-include-markdown-plugin = {version = "^1.0.0", optional = true}
mkdocs-material = {version = "^6.1.7", optional = true}
mkdocs-material-extensions = {version = "^1.0.1", optional = true}
mkdocstrings = {version = "^0.13.6", optional = true}
pip = {version = "^20.3.1", optional = true}
pre-commit = {version = "^2.12.0", optional = true}
pytest = {version = "6.1.2", optional = true}
pytest-cov = {version = "2.10.1", optional = true}
toml = {version = "^0.10.2", optional = true}
tox = {version = "^3.20.1", optional = true}
twine = {version = "^3.3.0", optional = true}
virtualenv = {version = "^20.2.2", optional = true}

[tool.poetry.extras]
test = [
  "pytest",
  "black",
  "isort",
  "flake8",
  "flake8-docstrings",
  "pytest-cov",
]

dev = ["tox", "pre-commit", "virtualenv", "pip", "twine", "toml"]

doc = [
  "mkdocs",
  "mkdocs-include-markdown-plugin",
  "mkdocs-material",
  "mkdocstrings",
  "mkdocs-material-extension",
  "mkdocs-autorefs",
]

[tool.poetry.scripts]
wibor-simulation = 'wibor_simulation.cli:main'

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 79
