[tool.poetry]
name = "sftputil"
version = "1.0.0"
description = "Advanced SFTP functions based on Paramiko"
authors = ["Romain TAPREST <romain@taprest.fr>"]

[tool.poetry.dependencies]
python = "^3.8"
paramiko = "^2.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
