# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sarus_data_spec/protobuf/scalar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%sarus_data_spec/protobuf/scalar.proto\x12\x0fsarus_data_spec\"\xa5\x05\n\x06Scalar\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x64oc\x18\x03 \x01(\t\x12*\n\x04spec\x18\x04 \x01(\x0b\x32\x1c.sarus_data_spec.Scalar.Spec\x12;\n\nproperties\x18\x05 \x03(\x0b\x32\'.sarus_data_spec.Scalar.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1az\n\x04Spec\x12:\n\x0btransformed\x18\x01 \x01(\x0b\x32#.sarus_data_spec.Scalar.TransformedH\x00\x12.\n\x05model\x18\x02 \x01(\x0b\x32\x1d.sarus_data_spec.Scalar.ModelH\x00\x42\x06\n\x04spec\x1a\xbc\x01\n\x0bTransformed\x12\x11\n\ttransform\x18\x01 \x01(\t\x12\x11\n\targuments\x18\x02 \x03(\t\x12P\n\x0fnamed_arguments\x18\x03 \x03(\x0b\x32\x37.sarus_data_spec.Scalar.Transformed.NamedArgumentsEntry\x1a\x35\n\x13NamedArgumentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x9a\x01\n\x05Model\x12\x11\n\targuments\x18\x01 \x01(\x0c\x12\x17\n\x0fnamed_arguments\x18\x02 \x01(\x0c\x12=\n\x0bmodel_class\x18\x03 \x01(\x0e\x32(.sarus_data_spec.Scalar.Model.ModelClass\"&\n\nModelClass\x12\x0c\n\x08TF_KERAS\x10\x00\x12\n\n\x06SK_SVC\x10\x01\x62\x06proto3')



_SCALAR = DESCRIPTOR.message_types_by_name['Scalar']
_SCALAR_PROPERTIESENTRY = _SCALAR.nested_types_by_name['PropertiesEntry']
_SCALAR_SPEC = _SCALAR.nested_types_by_name['Spec']
_SCALAR_TRANSFORMED = _SCALAR.nested_types_by_name['Transformed']
_SCALAR_TRANSFORMED_NAMEDARGUMENTSENTRY = _SCALAR_TRANSFORMED.nested_types_by_name['NamedArgumentsEntry']
_SCALAR_MODEL = _SCALAR.nested_types_by_name['Model']
_SCALAR_MODEL_MODELCLASS = _SCALAR_MODEL.enum_types_by_name['ModelClass']
Scalar = _reflection.GeneratedProtocolMessageType('Scalar', (_message.Message,), {

  'PropertiesEntry' : _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SCALAR_PROPERTIESENTRY,
    '__module__' : 'sarus_data_spec.protobuf.scalar_pb2'
    # @@protoc_insertion_point(class_scope:sarus_data_spec.Scalar.PropertiesEntry)
    })
  ,

  'Spec' : _reflection.GeneratedProtocolMessageType('Spec', (_message.Message,), {
    'DESCRIPTOR' : _SCALAR_SPEC,
    '__module__' : 'sarus_data_spec.protobuf.scalar_pb2'
    # @@protoc_insertion_point(class_scope:sarus_data_spec.Scalar.Spec)
    })
  ,

  'Transformed' : _reflection.GeneratedProtocolMessageType('Transformed', (_message.Message,), {

    'NamedArgumentsEntry' : _reflection.GeneratedProtocolMessageType('NamedArgumentsEntry', (_message.Message,), {
      'DESCRIPTOR' : _SCALAR_TRANSFORMED_NAMEDARGUMENTSENTRY,
      '__module__' : 'sarus_data_spec.protobuf.scalar_pb2'
      # @@protoc_insertion_point(class_scope:sarus_data_spec.Scalar.Transformed.NamedArgumentsEntry)
      })
    ,
    'DESCRIPTOR' : _SCALAR_TRANSFORMED,
    '__module__' : 'sarus_data_spec.protobuf.scalar_pb2'
    # @@protoc_insertion_point(class_scope:sarus_data_spec.Scalar.Transformed)
    })
  ,

  'Model' : _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
    'DESCRIPTOR' : _SCALAR_MODEL,
    '__module__' : 'sarus_data_spec.protobuf.scalar_pb2'
    # @@protoc_insertion_point(class_scope:sarus_data_spec.Scalar.Model)
    })
  ,
  'DESCRIPTOR' : _SCALAR,
  '__module__' : 'sarus_data_spec.protobuf.scalar_pb2'
  # @@protoc_insertion_point(class_scope:sarus_data_spec.Scalar)
  })
_sym_db.RegisterMessage(Scalar)
_sym_db.RegisterMessage(Scalar.PropertiesEntry)
_sym_db.RegisterMessage(Scalar.Spec)
_sym_db.RegisterMessage(Scalar.Transformed)
_sym_db.RegisterMessage(Scalar.Transformed.NamedArgumentsEntry)
_sym_db.RegisterMessage(Scalar.Model)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCALAR_PROPERTIESENTRY._options = None
  _SCALAR_PROPERTIESENTRY._serialized_options = b'8\001'
  _SCALAR_TRANSFORMED_NAMEDARGUMENTSENTRY._options = None
  _SCALAR_TRANSFORMED_NAMEDARGUMENTSENTRY._serialized_options = b'8\001'
  _SCALAR._serialized_start=59
  _SCALAR._serialized_end=736
  _SCALAR_PROPERTIESENTRY._serialized_start=215
  _SCALAR_PROPERTIESENTRY._serialized_end=264
  _SCALAR_SPEC._serialized_start=266
  _SCALAR_SPEC._serialized_end=388
  _SCALAR_TRANSFORMED._serialized_start=391
  _SCALAR_TRANSFORMED._serialized_end=579
  _SCALAR_TRANSFORMED_NAMEDARGUMENTSENTRY._serialized_start=526
  _SCALAR_TRANSFORMED_NAMEDARGUMENTSENTRY._serialized_end=579
  _SCALAR_MODEL._serialized_start=582
  _SCALAR_MODEL._serialized_end=736
  _SCALAR_MODEL_MODELCLASS._serialized_start=698
  _SCALAR_MODEL_MODELCLASS._serialized_end=736
# @@protoc_insertion_point(module_scope)
