# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sarus_data_spec/protobuf/status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%sarus_data_spec/protobuf/status.proto\x12\x0fsarus_data_spec\"\x9a\x04\n\x06Status\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x0f\n\x07manager\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\t\x12\x0c\n\x04task\x18\x05 \x01(\t\x12,\n\x05stage\x18\x06 \x01(\x0b\x32\x1d.sarus_data_spec.Status.Stage\x12;\n\nproperties\x18\x07 \x03(\x0b\x32\'.sarus_data_spec.Status.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\xa1\x02\n\x05Stage\x12\x38\n\x07pending\x18\x01 \x01(\x0b\x32%.sarus_data_spec.Status.Stage.PendingH\x00\x12>\n\nprocessing\x18\x02 \x01(\x0b\x32(.sarus_data_spec.Status.Stage.ProcessingH\x00\x12\x34\n\x05ready\x18\x03 \x01(\x0b\x32#.sarus_data_spec.Status.Stage.ReadyH\x00\x12\x34\n\x05\x65rror\x18\x04 \x01(\x0b\x32#.sarus_data_spec.Status.Stage.ErrorH\x00\x1a\t\n\x07Pending\x1a\x0c\n\nProcessing\x1a\x07\n\x05Ready\x1a\x07\n\x05\x45rrorB\x07\n\x05stageb\x06proto3')



_STATUS = DESCRIPTOR.message_types_by_name['Status']
_STATUS_PROPERTIESENTRY = _STATUS.nested_types_by_name['PropertiesEntry']
_STATUS_STAGE = _STATUS.nested_types_by_name['Stage']
_STATUS_STAGE_PENDING = _STATUS_STAGE.nested_types_by_name['Pending']
_STATUS_STAGE_PROCESSING = _STATUS_STAGE.nested_types_by_name['Processing']
_STATUS_STAGE_READY = _STATUS_STAGE.nested_types_by_name['Ready']
_STATUS_STAGE_ERROR = _STATUS_STAGE.nested_types_by_name['Error']
Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {

  'PropertiesEntry' : _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATUS_PROPERTIESENTRY,
    '__module__' : 'sarus_data_spec.protobuf.status_pb2'
    # @@protoc_insertion_point(class_scope:sarus_data_spec.Status.PropertiesEntry)
    })
  ,

  'Stage' : _reflection.GeneratedProtocolMessageType('Stage', (_message.Message,), {

    'Pending' : _reflection.GeneratedProtocolMessageType('Pending', (_message.Message,), {
      'DESCRIPTOR' : _STATUS_STAGE_PENDING,
      '__module__' : 'sarus_data_spec.protobuf.status_pb2'
      # @@protoc_insertion_point(class_scope:sarus_data_spec.Status.Stage.Pending)
      })
    ,

    'Processing' : _reflection.GeneratedProtocolMessageType('Processing', (_message.Message,), {
      'DESCRIPTOR' : _STATUS_STAGE_PROCESSING,
      '__module__' : 'sarus_data_spec.protobuf.status_pb2'
      # @@protoc_insertion_point(class_scope:sarus_data_spec.Status.Stage.Processing)
      })
    ,

    'Ready' : _reflection.GeneratedProtocolMessageType('Ready', (_message.Message,), {
      'DESCRIPTOR' : _STATUS_STAGE_READY,
      '__module__' : 'sarus_data_spec.protobuf.status_pb2'
      # @@protoc_insertion_point(class_scope:sarus_data_spec.Status.Stage.Ready)
      })
    ,

    'Error' : _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
      'DESCRIPTOR' : _STATUS_STAGE_ERROR,
      '__module__' : 'sarus_data_spec.protobuf.status_pb2'
      # @@protoc_insertion_point(class_scope:sarus_data_spec.Status.Stage.Error)
      })
    ,
    'DESCRIPTOR' : _STATUS_STAGE,
    '__module__' : 'sarus_data_spec.protobuf.status_pb2'
    # @@protoc_insertion_point(class_scope:sarus_data_spec.Status.Stage)
    })
  ,
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'sarus_data_spec.protobuf.status_pb2'
  # @@protoc_insertion_point(class_scope:sarus_data_spec.Status)
  })
_sym_db.RegisterMessage(Status)
_sym_db.RegisterMessage(Status.PropertiesEntry)
_sym_db.RegisterMessage(Status.Stage)
_sym_db.RegisterMessage(Status.Stage.Pending)
_sym_db.RegisterMessage(Status.Stage.Processing)
_sym_db.RegisterMessage(Status.Stage.Ready)
_sym_db.RegisterMessage(Status.Stage.Error)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS_PROPERTIESENTRY._options = None
  _STATUS_PROPERTIESENTRY._serialized_options = b'8\001'
  _STATUS._serialized_start=59
  _STATUS._serialized_end=597
  _STATUS_PROPERTIESENTRY._serialized_start=256
  _STATUS_PROPERTIESENTRY._serialized_end=305
  _STATUS_STAGE._serialized_start=308
  _STATUS_STAGE._serialized_end=597
  _STATUS_STAGE_PENDING._serialized_start=547
  _STATUS_STAGE_PENDING._serialized_end=556
  _STATUS_STAGE_PROCESSING._serialized_start=558
  _STATUS_STAGE_PROCESSING._serialized_end=570
  _STATUS_STAGE_READY._serialized_start=572
  _STATUS_STAGE_READY._serialized_end=579
  _STATUS_STAGE_ERROR._serialized_start=581
  _STATUS_STAGE_ERROR._serialized_end=588
# @@protoc_insertion_point(module_scope)
