language: python - "3.8"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create env
  - conda create -q -n test-environment python=3.8
  - conda activate test-environment

# command to install dependencies
install:
  - conda install cython numpy pytest
  - pip install git+https://github.com/morris-lab/CellOracle.git
# command to run tests
script:
  - pytest
