
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T11:12:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3b6cee3340dcf9994d33da42703cfe4bc2f5304",
 "version": "0.7.1.post.dev553"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
