# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/aggregate_feature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layer.api.entity import aggregation_pb2 as api_dot_entity_dot_aggregation__pb2
from layer.api import ids_pb2 as api_dot_ids__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"api/entity/aggregate_feature.proto\x12\x03\x61pi\x1a\x1c\x61pi/entity/aggregation.proto\x1a\rapi/ids.proto\"\xab\x02\n\x10\x41ggregateFeature\x12\x1a\n\x02id\x18\x01 \x01(\x0b\x32\x0e.api.FeatureId\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\"\n\rcreated_by_id\x18\x04 \x01(\x0b\x32\x0b.api.UserId\x12\x19\n\x11\x63reated_timestamp\x18\x05 \x01(\x06\x12\x19\n\x11updated_timestamp\x18\x06 \x01(\x06\x12,\n\x0forganization_id\x18\x07 \x01(\x0b\x32\x13.api.OrganizationId\x12)\n\x11parent_feature_id\x18\x08 \x01(\x0b\x32\x0e.api.FeatureId\x12%\n\x0b\x61ggregation\x18\t \x01(\x0b\x32\x10.api.AggregationB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_AGGREGATEFEATURE = DESCRIPTOR.message_types_by_name['AggregateFeature']
AggregateFeature = _reflection.GeneratedProtocolMessageType('AggregateFeature', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEFEATURE,
  '__module__' : 'api.entity.aggregate_feature_pb2'
  # @@protoc_insertion_point(class_scope:api.AggregateFeature)
  })
_sym_db.RegisterMessage(AggregateFeature)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _AGGREGATEFEATURE._serialized_start=89
  _AGGREGATEFEATURE._serialized_end=388
# @@protoc_insertion_point(module_scope)
