"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layer.api.entity.aggregate_feature_pb2
import layer.api.entity.python_feature_pb2
import layer.api.entity.spark_feature_pb2
import layer.api.entity.sql_feature_pb2
import layer.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class FeatureSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SQL_FEATURES_FIELD_NUMBER: builtins.int
    CREATED_BY_ID_FIELD_NUMBER: builtins.int
    CREATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    UPDATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    PYTHON_FEATURES_FIELD_NUMBER: builtins.int
    AGGREGATE_FEATURES_FIELD_NUMBER: builtins.int
    TARGET_DATA_SOURCE_ID_FIELD_NUMBER: builtins.int
    SPARK_FEATURES_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    PROJECT_NAME_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> api.ids_pb2.FeatureSetId: ...
    name: typing.Text
    @property
    def sql_features(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.entity.sql_feature_pb2.SqlFeature]: ...
    @property
    def created_by_id(self) -> api.ids_pb2.UserId: ...
    created_timestamp: builtins.int
    updated_timestamp: builtins.int
    @property
    def organization_id(self) -> api.ids_pb2.OrganizationId: ...
    description: typing.Text
    @property
    def python_features(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.entity.python_feature_pb2.PythonFeature]: ...
    @property
    def aggregate_features(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.entity.aggregate_feature_pb2.AggregateFeature]: ...
    @property
    def target_data_source_id(self) -> api.ids_pb2.DataSourceId: ...
    @property
    def spark_features(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[api.entity.spark_feature_pb2.SparkFeature]: ...
    @property
    def project_id(self) -> api.ids_pb2.ProjectId: ...
    project_name: typing.Text
    def __init__(self,
        *,
        id: typing.Optional[api.ids_pb2.FeatureSetId] = ...,
        name: typing.Text = ...,
        sql_features: typing.Optional[typing.Iterable[api.entity.sql_feature_pb2.SqlFeature]] = ...,
        created_by_id: typing.Optional[api.ids_pb2.UserId] = ...,
        created_timestamp: builtins.int = ...,
        updated_timestamp: builtins.int = ...,
        organization_id: typing.Optional[api.ids_pb2.OrganizationId] = ...,
        description: typing.Text = ...,
        python_features: typing.Optional[typing.Iterable[api.entity.python_feature_pb2.PythonFeature]] = ...,
        aggregate_features: typing.Optional[typing.Iterable[api.entity.aggregate_feature_pb2.AggregateFeature]] = ...,
        target_data_source_id: typing.Optional[api.ids_pb2.DataSourceId] = ...,
        spark_features: typing.Optional[typing.Iterable[api.entity.spark_feature_pb2.SparkFeature]] = ...,
        project_id: typing.Optional[api.ids_pb2.ProjectId] = ...,
        project_name: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_by_id",b"created_by_id","id",b"id","organization_id",b"organization_id","project_id",b"project_id","target_data_source_id",b"target_data_source_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aggregate_features",b"aggregate_features","created_by_id",b"created_by_id","created_timestamp",b"created_timestamp","description",b"description","id",b"id","name",b"name","organization_id",b"organization_id","project_id",b"project_id","project_name",b"project_name","python_features",b"python_features","spark_features",b"spark_features","sql_features",b"sql_features","target_data_source_id",b"target_data_source_id","updated_timestamp",b"updated_timestamp"]) -> None: ...
global___FeatureSet = FeatureSet
