# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/python_feature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layer.api.entity import aggregation_pb2 as api_dot_entity_dot_aggregation__pb2
from layer.api import ids_pb2 as api_dot_ids__pb2
from layer.api.value import s3_path_pb2 as api_dot_value_dot_s3__path__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61pi/entity/python_feature.proto\x12\x03\x61pi\x1a\x1c\x61pi/entity/aggregation.proto\x1a\rapi/ids.proto\x1a\x17\x61pi/value/s3_path.proto\"\x88\x03\n\rPythonFeature\x12\x1a\n\x02id\x18\x01 \x01(\x0b\x32\x0e.api.FeatureId\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\rpython_source\x18\x03 \x01(\tB\x02\x18\x01\x12\x1c\n\x07s3_path\x18\x04 \x01(\x0b\x32\x0b.api.S3Path\x12\"\n\rcreated_by_id\x18\x05 \x01(\x0b\x32\x0b.api.UserId\x12\x19\n\x11\x63reated_timestamp\x18\x06 \x01(\x06\x12\x19\n\x11updated_timestamp\x18\x07 \x01(\x06\x12,\n\x0forganization_id\x18\x08 \x01(\x0b\x32\x13.api.OrganizationId\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12 \n\x18python_source_entrypoint\x18\n \x01(\t\x12\x1d\n\x15python_source_content\x18\x0b \x01(\t\x12&\n\x0c\x61ggregations\x18\x0c \x03(\x0b\x32\x10.api.Aggregation\x12\x0e\n\x06\x66\x61\x62ric\x18\r \x01(\tB\x11\n\rcom.layer.apiP\x01\x62\x06proto3')



_PYTHONFEATURE = DESCRIPTOR.message_types_by_name['PythonFeature']
PythonFeature = _reflection.GeneratedProtocolMessageType('PythonFeature', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONFEATURE,
  '__module__' : 'api.entity.python_feature_pb2'
  # @@protoc_insertion_point(class_scope:api.PythonFeature)
  })
_sym_db.RegisterMessage(PythonFeature)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.layer.apiP\001'
  _PYTHONFEATURE.fields_by_name['python_source']._options = None
  _PYTHONFEATURE.fields_by_name['python_source']._serialized_options = b'\030\001'
  _PYTHONFEATURE._serialized_start=111
  _PYTHONFEATURE._serialized_end=503
# @@protoc_insertion_point(module_scope)
