[tool.poetry]
name = "idmhelpers"
version = "0.1.2"
description = "Helper library for common Databricks activities for Data Engineering, Delta Tables, Pipelines"
authors = ["divyavanmahajan <divya.mahajan@outlook.com>"]

[tool.poetry.dependencies]
python = "*"
pyspark = "^3"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
