[tool.poetry]
name = "thousandwords.core"
version = "0.4.0"
description = ""
authors = ["Gai Luron <gai.luron.1964@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
cloudpickle = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pandas = "1.3.5"
sklearn = "^0.0"
numpy = "1.21.6"
matplotlib = "3.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
