[tool.poetry]
name = "om_helper"
version = "0.0.16"
description = "om`s helper"
authors = ["iulmt <1817556010@qq.com>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
