require "style.amenity"
require "style.building"
require "style.indoor"
require "style.infrastructure"
require "style.landuse"
require "style.leisure"
require "style.natural"
require "style.place"
require "style.poi"
require "style.public_transport"
require "style.road"
require "style.road_major"
require "style.shop"
require "style.tags"
require "style.traffic"
require "style.water"

-- `unitable` is a dump of all features. Useful for debugging purposes, uncomment to include
-- require "style.unitable"