[tool.poetry]
name = "Lespy"
license = "MIT"
version = "0.1.2"
authors = ["Natan Santos <natansantosapps@gmail.com>"]
description = "A small and robust micro Python framework for building simple and solid web apps."
readme = "README.md"

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: WSGI",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.urls]
"Source" = "https://github.com/natanfeitosa/lespy/"
"Tracker" = "https://github.com/natanfeitosa/lespy/issues/"

[tool.poetry.dependencies]
python = "^3.8"
pyfunctools = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.942"
mkdocs = {extras = ["i18n"], version = "^1.3.0"}
mkdocs-material = "^8.2.9"
ipython = "^8.2.0"
twine = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
