- project:
    templates:
      - check-requirements
      # FIXME: see https://review.opendev.org/747460
      # - lib-forward-testing-python3
      - openstack-cover-jobs
      # FIXME: add lower-constraints or drop this
      # - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
