[tool.poetry]
name = "invertedai-simulate"
version = "1.0.5"
description = "Client Interface for InvertedAI Simulate"
authors = ["Inverted AI <info@inverted.ai>"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]
readme = "README.md"
packages = [
    { include = "invertedai_simulate" },
]


[tool.poetry.dependencies]
python = ">=3.7.1, <3.11"
packaging = "^21.0"
pygame = ">=2.0.0"
gym = ">=0.17.2,<1.0.0"
matplotlib = "==3.5.1"
pyzmq = "==22.3.0"
scikit-image = "==0.19.2"
SQLAlchemy = "==1.4.31"
iai_common = "==1.0.3"
halo = "==0.0.31"
imageio-ffmpeg = "^0.4.7"
Sphinx = { version = "==4.5.0", optional = false }
sphinx-rtd-theme = { version = "==1.0.0", optional = false }
sphinx-copybutton = { version = "==0.5.0", optional = false }
sphinx-design = { version = "==0.1.0", optional = false }
furo = { version = "==2022.4.7", optional = false }
myst-parser = { version = "==0.17.2", optional = false }
sphinxcontrib-applehelp  = { version = "==1.0.2", optional = false }
sphinxcontrib-devhelp = { version = "==1.0.2", optional = false }
sphinxcontrib-htmlhelp = { version = "==2.0.0", optional = false }
sphinxcontrib-jsmath = { version = "==1.0.1", optional = false }
sphinxcontrib-qthelp = { version = "==1.0.3", optional = false }
sphinxcontrib-serializinghtml = { version = "==1.1.5", optional = false }
inquirer = "^2.9.2"

[tool.poetry.dev-dependencies]
twine = "==4.0.0"

# [tool.poetry.group.test]
#
# [tool.poetry.group.test.dependencies]
# pytest = "^6.0.0"
# pytest-mock = "*"

[tool.poetry.extras]
# docs = ["sphinx", "sphinx_rtd_theme", "sphinx-copybutton", "sphinx-design", "furo", "myst-parser",
# "sphinxcontrib-applehelp", "sphinxcontrib-devhelp", "sphinxcontrib-htmlhelp", "sphinxcontrib-jsmath",
# "sphinxcontrib-qthelp", "sphinxcontrib-serializinghtml"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
