
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-06T16:04:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "94df22a807c16476aecdc357ea72e3f7ed037f18",
 "version": "v0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
