[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "matplotlib",
    "wxpython",
    "pyopengl",
    "pandas",
    "scipy",
    "pillow",
    "owslib",
	"cython",
	"pyproj",
	"dbfread",
	"graphviz",
	"owslib",
	"typing",
	"requests",
	"beautifulsoup4"
]
build-backend = "setuptools.build_meta"