name: glearn
channels:
  - gammalearn
  - cta-observatory
  - conda-forge
  - anaconda
  - defaults
  - pytorch
  - nvidia
  - ctlearn-project
dependencies:
  - python=3.8
  - pip
  - pytorch
  - torchvision
  - nvidia::cudatoolkit>=11.1
  - pytorch-lightning>=1.6
  - ctapipe=0.10
  - matplotlib
  - pandas
  - pytables
  - astropy
  - dl1_data_handler=0.10
  - gammapy=0.18.2
  - pip:
    - indexedconv>=1.3
    - ctaplot
    - "lstchain>=0.7,<0.8"
    - torch-tb-profiler
