
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T11:52:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "94edb240c995b2880342564e3d9f09d29eae4a40",
 "version": "0.7.1.post.dev561"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
