# https://python-poetry.org/docs/pyproject/

[tool.poetry]
name = "pomalevi"
version = "1.0"
description = "Powerpoint-based maintainable lecture videos"
authors = ["Lutz Prechelt <prechelt@inf.fu-berlin.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/prechelt/pomalevi/blob/main/README.md"
repository = "https://github.com/prechelt/pomalevi"
keywords = ["Powerpoint", "video editing", "video rendering", "video player"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Multimedia :: Video :: Conversion",
    "Topic :: Multimedia :: Video :: Display",
    "Topic :: Utilities",
]

packages = [
    { include = "pmlv" }
]
include = ["README.md", "poetry.lock", 
           "css/*", "img/*", "test/**", ]
exclude = ["**/*~"]


[tool.poetry.scripts]
pomalevi = "pmlv.main:doitall"
static_ffmpeg = "static_ffmpeg.run:main_static_ffmpeg"
static_ffprobe = "static_ffmpeg.run:main_static_ffprobe"


[tool.poetry.dependencies]
python = "^3.8"
attrs = "^21"
static-ffmpeg = "^2.2"


[tool.poetry.dev-dependencies]
pytest = "^7"
# PyCharm setup: https://www.jetbrains.com/help/pycharm/poetry.html


[tool.pytest.ini_options]
python_files = ["tests.py", "*_test.py"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
