[tool.poetry]
name = "lakedrive"
version = "0.1.0"
description = ""
authors = ["anthony <anthony.potappel@gmail.com>"]
packages = [
    { include = "lakedrive", from = "src" },
    { include = "lakedrive/py.typed", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
coverage = "^6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = "^21.12b0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
