
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-06T09:46:14-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a011907cc2f1673ad1d12675e6547b204a01a01",
 "version": "v1.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
