# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/usage/v1/usage_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from strmprivacy.api.entities.v1 import entities_v1_pb2 as strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'strmprivacy/api/usage/v1/usage_v1.proto\x12\x18strmprivacy.api.usage.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a-strmprivacy/api/entities/v1/entities_v1.proto\"\xdc\x01\n\x1aGetStreamEventUsageRequest\x12\x33\n\x03ref\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.StreamRef\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x08interval\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\"\x94\x01\n\x1bGetStreamEventUsageResponse\x12\x33\n\x03ref\x18\x01 \x01(\x0b\x32&.strmprivacy.api.entities.v1.StreamRef\x12@\n\x07windows\x18\x02 \x03(\x0b\x32/.strmprivacy.api.entities.v1.WindowedEventCount2\x93\x01\n\x0cUsageService\x12\x82\x01\n\x13GetStreamEventUsage\x12\x34.strmprivacy.api.usage.v1.GetStreamEventUsageRequest\x1a\x35.strmprivacy.api.usage.v1.GetStreamEventUsageResponseB`\n\x1bio.strmprivacy.api.usage.v1P\x01Z?github.com/strmprivacy/api-definitions-go/v2/api/usage/v1;usageb\x06proto3')



_GETSTREAMEVENTUSAGEREQUEST = DESCRIPTOR.message_types_by_name['GetStreamEventUsageRequest']
_GETSTREAMEVENTUSAGERESPONSE = DESCRIPTOR.message_types_by_name['GetStreamEventUsageResponse']
GetStreamEventUsageRequest = _reflection.GeneratedProtocolMessageType('GetStreamEventUsageRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMEVENTUSAGEREQUEST,
  '__module__' : 'strmprivacy.api.usage.v1.usage_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.usage.v1.GetStreamEventUsageRequest)
  })
_sym_db.RegisterMessage(GetStreamEventUsageRequest)

GetStreamEventUsageResponse = _reflection.GeneratedProtocolMessageType('GetStreamEventUsageResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMEVENTUSAGERESPONSE,
  '__module__' : 'strmprivacy.api.usage.v1.usage_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.usage.v1.GetStreamEventUsageResponse)
  })
_sym_db.RegisterMessage(GetStreamEventUsageResponse)

_USAGESERVICE = DESCRIPTOR.services_by_name['UsageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.strmprivacy.api.usage.v1P\001Z?github.com/strmprivacy/api-definitions-go/v2/api/usage/v1;usage'
  _GETSTREAMEVENTUSAGEREQUEST._serialized_start=182
  _GETSTREAMEVENTUSAGEREQUEST._serialized_end=402
  _GETSTREAMEVENTUSAGERESPONSE._serialized_start=405
  _GETSTREAMEVENTUSAGERESPONSE._serialized_end=553
  _USAGESERVICE._serialized_start=556
  _USAGESERVICE._serialized_end=703
# @@protoc_insertion_point(module_scope)
