"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: 0.5.0-SNAPSHOT
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


import unittest

import pds.api_client
from pds.api_client.api.products_api import ProductsApi  # noqa: E501


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_products(self):
        """Test case for products

        search across all PDS data products, including bundles, collections, documentation, context and observational products,  # noqa: E501
        """
        pass

    def test_products_by_lidvid(self):
        """Test case for products_by_lidvid

        URN resolver for lidvid  # noqa: E501
        """
        pass

    def test_products_by_lidvid_all(self):
        """Test case for products_by_lidvid_all

        Get one product by lidvid, or all versions of a product by lid  # noqa: E501
        """
        pass

    def test_products_by_lidvid_latest(self):
        """Test case for products_by_lidvid_latest

        URN resolver for lidvid  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
