"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: 0.5.0-SNAPSHOT
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pds.api_client
from pds.api_client.model.pds4_metadata_data_files import Pds4MetadataDataFiles
from pds.api_client.model.pds4_metadata_label_file import Pds4MetadataLabelFile
globals()['Pds4MetadataDataFiles'] = Pds4MetadataDataFiles
globals()['Pds4MetadataLabelFile'] = Pds4MetadataLabelFile
from pds.api_client.model.pds4_metadata import Pds4Metadata


class TestPds4Metadata(unittest.TestCase):
    """Pds4Metadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPds4Metadata(self):
        """Test Pds4Metadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Pds4Metadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
