"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: 0.5.0-SNAPSHOT
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pds.api_client
from pds.api_client.model.pds4_product import Pds4Product
from pds.api_client.model.summary import Summary
globals()['Pds4Product'] = Pds4Product
globals()['Summary'] = Summary
from pds.api_client.model.pds4_products import Pds4Products


class TestPds4Products(unittest.TestCase):
    """Pds4Products unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPds4Products(self):
        """Test Pds4Products"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Pds4Products()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
