"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: 0.5.0-SNAPSHOT
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pds.api_client
from pds.api_client.model.pds4_metadata import Pds4Metadata
globals()['Pds4Metadata'] = Pds4Metadata
from pds.api_client.model.pds4_product import Pds4Product


class TestPds4Product(unittest.TestCase):
    """Pds4Product unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPds4Product(self):
        """Test Pds4Product"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Pds4Product()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
