"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: 0.5.0-SNAPSHOT
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pds.api_client
from pds.api_client.model.pds4_metadata_data_files import Pds4MetadataDataFiles


class TestPds4MetadataDataFiles(unittest.TestCase):
    """Pds4MetadataDataFiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPds4MetadataDataFiles(self):
        """Test Pds4MetadataDataFiles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Pds4MetadataDataFiles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
