[tool.poetry]
name = "visvasc"
version = "0.1.0"
description = "A visualation tool for vasculature pressure and flow."
authors = ["Alex <adrysdale@protonmail.com>"]
license = "GPLv3+"
repository = "https://gitlab.com/abdrysdale/vis-vasc"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
plotly = "^5.7.0"
dash = "^2.3.1"
numpy = "^1.22.3"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
