[tool.poetry]
name = "pyspark-dataframe-extras"
version = "0.0.1"
description = "Utility functions for PySpark"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^4.0.1"
mypy = "^0.950"
chispa = "^0.9.2"
pyspark = "^3.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
