
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-05T13:37:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "df81ff3c320dc1e7ab50705e9e4051482ae0ce13",
 "version": "0.15.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
