
## MC PRODUCTION FULL PIPELINE CONFIGURATION ##
#
# This config can be used to rerun a MC analysis with different settings.
# In contrast to the normal analysis, lstchain_dl1ab will be used and the 
# analysis starts with dl1a files.
# For this to work, a reference analysis needs to be set as this will act as input.
# The reference analysis has to be processed using no_image: False
# Optionally, observed files can be referenced as well to automatically
# calculate the fine-tuning parameters for the dl1ab step.
# See https://github.com/cta-observatory/cta-lstchain/blob/master/lstchain/scripts/lstchain_tune_nsb.py for details.
#

# Standard settings:
workflow_kind: lstchain  
# A prod id should be set in this case to differentiate from the reference analysis
# Dummy:
prod_id: ref_id_tune_MC_to_$SOURCE

particles:
  - electron
  - gamma
  - gamma-diffuse
  - proton
offset_gammas:
  - off0.0deg
  - off0.4deg

source_environment:
  source_file: /fefs/aswg/software/conda/etc/profile.d/conda.sh
  conda_env: lstchain-v0.9.2

base_path: /fefs/aswg/workspace/MC_data_simlink  # Default user path
  # lstanalyzer user : /fefs/aswg/data/mc
prod_type: prod5
obs_date: 20200629_prod5_trans_80
zenith: zenith_20deg
pointing: south_pointing

merging_options:
  no_image: True

slurm_config:
  user_account: aswg

## DL1AB related settings

# Set dl1ab as first step
stages_to_run:
  - dl1ab
  - merge_and_copy_dl1
  - train_pipe
  - dl1_to_dl2
  - dl2_to_irfs
  - dl2_to_sensitivity

# Configure these according to your needs!
# Set the path to a reference_production
dl1_reference_id: 20220215_v0.9.1_prod5_trans_80_local_tailcut_8_4

# If the image modifier settings should be calculated on the fly
# set paths to an observed dl1 file and a simtel mc file
dl1_noise_tune_data_run: /fefs/aswg/data/real/DL1/20201121/v0.9.1/tailcut84/dl1_LST-1.Run02988.0000.h5
dl1_noise_tune_mc_run: /fefs/aswg/data/mc/DL0/20200629_prod5_trans_80/proton/zenith_20deg/south_pointing/proton_20deg_180deg_run1___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono.simtel.gz

