# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\py-client\couchbase_version.py
# at
#    2022-05-05 20:25:52.844795
__version__ = '4.0.0rc1'