[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stvh"
version = "0.0.19"
description = "a collection useful tools"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
  {name = "Steven Yan-Jia Huang", email = "s@stvhuang.me"}
]
maintainers = [
  {name = "Steven Yan-Jia Huang", email = "s@stvhuang.me"}
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]
dependencies = [
  "numpy",
  "requests",
  "scikit-learn",
]

[project.optional-dependencies]
test = [
  "pytest",
]
