[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "certifi",
    "chardet",
    "idna",
    "PySocks",
    "python-dateutil",
    "requests",
    "six",
    "urllib3"
]
build-backend = "setuptools.build_meta"