[build-system]
requires = ["flit_core ~=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "pyrutext"
authors = [{name = "Belreau Cohen", email = "nuu.chah.nulth@disroot.org"}]
readme = "README.md"
dynamic = ["version", "description"]
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "pyyaml ~=6.0",
    "aioconsole ~=0.4",
]

[project.urls]
Home = "https://github.com/Belstowe/py-rutext.git"

[tool.flit.sdist]
exclude = [".github/"]