[package]
name = "cameo_ocean"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cameo_ocean"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.4", features = ["extension-module"] }
actix-web = { version = "4.0.1", features = ["openssl"] }
openssl = { version = "0.10.38", features = ["v110"] }
actix-rt = "2.7.0"
serde = { version = "1.0.136", features = ["derive"] }
simple_logger = "1.6.0"
log = "0.4.8"
pam = "0.7.0"
actix-multipart = "0.4.0"
futures = "0.3.1"
sanitize-filename = "0.2"
chrono = "0.4.19"
actix-files = "0.6.0"
actix-cors = "0.6.1"
rmp-serde = "1.1.0"
serde_json = "1.0.79"
substring = "1.4.5"
lz4 = "1.23.3"