
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-06T13:54:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5624a0e68e312df8ffe1b9eb0a37112f4ce503c",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
