[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 120


[tool.isort]
known_third_party = []

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov=tlvis"
testpaths = [
    "tests",
    "src",
]