
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-29T16:37:27+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0d0783f214c1378b10d00ffdc1391cefbbd7cb3",
 "version": "0.27.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
