[tool.poetry]
name = "aide_infra"
packages = [
    {include = "aide"}
]
version = "0.3.1.2"
description = ""
authors = ["Josh Liberty <josh.liberty@answerdigital.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pika = "^1.2.0"
pynetdicom = "1.5.7"
pydicom = "2.1.2"

[tool.poetry.dev-dependencies]
pylint = "^2.10.2"
flake8 = "^3.9.2"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
