[tool.poetry]
name = "poetry-example-dg"
version = "0.1.0"
description = ""
authors = ["David Griffiths <davidgg777@hotmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/wisemuffin/poetry-example-dg"
repository = "https://github.com/wisemuffin/poetry-example-dg"
keywords = ["wisemuffin"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
eve = 'poetry_example_dg.cli:cli'
