[tool.poetry]
name = "requests-http-message-signatures"
version = "0.3.1"
description = "A request authentication plugin implementing IETF HTTP Message Signatures"
readme = "README.md"
homepage = "https://dev.funkwhale.audio/funkwhale/requests-http-message-signatures"
license = "Apache-2.0"
authors = ["Andrey Kislyuk", "Funkwhale Collective <maintainers@funkwhale.audio>"]
classifiers = [
	'Intended Audience :: Developers',
	'License :: OSI Approved :: Apache Software License',
	'Operating System :: MacOS :: MacOS X',
	'Operating System :: POSIX',
	'Programming Language :: Python',
	'Development Status :: 5 - Production/Stable',
	'Topic :: Software Development :: Libraries :: Python Modules'
]

[tool.poetry.dependencies]
python = "^3.7"
cryptography = ">=1.8.2"
requests = "^2"

[tool.poetry.dev-dependencies]
Sphinx = "^4.5.0"
coverage = "^6.3.2"
myst-parser = "^0.17.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
