[tool.poetry]
name = "terality"
version = "0.14.21"
description = "The Data Processing Engine for Data Scientists"
authors = ["Terality Engineering Team <dev.null@terality.com>"]
license = "Proprietary"
readme = "README.md"
homepage = "https://terality.com/"
packages = [
    { include = "terality" },
    { include = "terality_serde" },
    { include = "common_client_scheduler" },
]

[tool.poetry.dependencies]
python = "^3.7.1"
pyarrow = "^6.0.0"
numpy = "^1.18"
pandas = "^1.0.0"
requests = "^2.23.0"
pydantic = "^1.7.3"
boto3 = ">=1.16.28"
azure-storage-file-datalake = {version = "^12.4.0", optional = true}
azure-storage-blob = {version = "^12.8.1", optional = true}
azure-identity = {version = "^1.6.0", optional = true}
sentry-sdk = "^1.3.0"
click = ">= 3.2, <9"
protobuf = "^3.9.1"
tqdm = "^4.45.0"
importlib_metadata = {version = ">= 3.0, <5", python = "< 3.8" }

[tool.poetry.extras]
azure = ["azure-storage-blob", "azure-storage-file-datalake", "azure-identity"]

[tool.poetry.dev-dependencies]
mypy = "^0.790"
pytest = "^5.4.3"
vendorize = "^0.2.2"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
terality = 'terality._terality.bin.__main__:cli'
