[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4", "setuptools_scm_git_archive"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "gbprocess/version.py"

[tool.black]
target-version = ['py38', 'py39', 'py310']
line_length = 100
exclude = '''
(
  \.egg
  | \.git
  | \.venv
  | _build
  | build
  | dist
)
'''