version: "3.4"

services:
  app:
    dns: 192.168.100.29
    environment:
      - SWH_CONFIG_FILENAME=config/staging.yml
    command: uvicorn swh.graphql.server:make_app_from_configfile --host 0.0.0.0 --port 8000 --reload
