VERSION_YEAR = 2022
VERSION_MONTH = int('05')
VERSION_DAY = int('03')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('17')
MAJOR_VERSION = 2
MINOR_VERSION = 12
PATCH_VERSION = 202205030817
version_date = '2022/05/03 08:17'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
