# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\py-client\couchbase_version.py
# at
#    2022-05-05 22:20:27.022396
__version__ = '4.0.0'