[tool.poetry]
name = "aiopaykassa"
version = "0.0.1a3"
description = "Paykassa.pro asyncio python client"
authors = ["drforse <george.lifeslice@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/drforse/aiopaykassa"
repository = "https://github.com/drforse/aiopaykassa"
classifiers = [
    "Framework :: AsyncIO",
    "Framework :: aiohttp",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.1"
pydantic = "^1.9.0"
ujson = {version = "^5.2.0", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
ujson = ["ujson"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
