[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rfc6902-types"
version = "0.1.0"
description = "Types aliases for RFC6902-compliant dicts"
authors = [{name = "Léo El Amri", email = "leo@superlel.me"}]
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]

[tool.flit.module]
name = "rfc6902_types"
