[tool.poetry]
name = "basic_iter"
version = "0.0.4"
description = "A basic set of functions on iterators"
authors = ["Takayuki Goto <nephits@gmail.com>"]
maintainers = ["Takayuki Goto <nephits@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
hypothesis = "^6.39.0"
pylint = "^2.13.5"
yapf = "^0.32.0"
toml = "^0.10.2"
mypy = "^0.942"
sphinx = "^4.5.0"

[tool.yapf]
based_on_style = "google"
column_limit = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
