VERSION_YEAR = 2022
VERSION_MONTH = int('05')
VERSION_DAY = int('04')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('30')
MAJOR_VERSION = 1
MINOR_VERSION = 8
PATCH_VERSION = 202205040530
version_date = '2022/05/04 05:30'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
