# Form implementation generated from reading ui file '/home/detlev/Development/Python/Eric/eric7-22.5/eric/eric7/PyUnit/UnittestStacktraceDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UnittestStacktraceDialog(object):
    def setupUi(self, UnittestStacktraceDialog):
        UnittestStacktraceDialog.setObjectName("UnittestStacktraceDialog")
        UnittestStacktraceDialog.resize(600, 250)
        self.vboxlayout = QtWidgets.QVBoxLayout(UnittestStacktraceDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.testLabel = QtWidgets.QLabel(UnittestStacktraceDialog)
        self.testLabel.setObjectName("testLabel")
        self.vboxlayout.addWidget(self.testLabel)
        self.traceback = QtWidgets.QTextEdit(UnittestStacktraceDialog)
        self.traceback.setReadOnly(True)
        self.traceback.setAcceptRichText(False)
        self.traceback.setObjectName("traceback")
        self.vboxlayout.addWidget(self.traceback)
        self.buttonBox = QtWidgets.QDialogButtonBox(UnittestStacktraceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(UnittestStacktraceDialog)
        self.buttonBox.accepted.connect(UnittestStacktraceDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(UnittestStacktraceDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UnittestStacktraceDialog)

    def retranslateUi(self, UnittestStacktraceDialog):
        pass
