DEFAULT_ADDRESS = "127.0.0.1"
DEFAULT_PORT = 7777
DEFAULT_NAME = ''

MAX_CLIENTS = 1
MAX_LENGTH_BYTES = 1024
DECODING_FORMAT = 'utf-8'

LOGGING_LEVEL_CLIENT = "DEBUG"
LOGGING_LEVEL_SERVER = "DEBUG"
STREAM_LEVEL = 'INFO'
VERSION = "0.10"
