
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-03T08:34:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b98dcabc6002c17080c0d48c7cc81f3ee71cc07",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
