[tool.poetry]
name = "ilpincometax"
version = "0.1.2"
description = "library for calculating US federal tax for 2022, this is my personal project so do not recommend to use in production scenario with out testing"
authors = ["iluvpython <iluvpython@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
