[tool.poetry]
name = "hybridmethods"
version = "0.1.2"
authors = ["Dense Reptile <80247368+DenseReptile@users.noreply.github.com>"]
description = "Library to create hybrids of class methods and instance methods"
license = "0BSD"
keywords = ["hybridmethod", "method", "methods", "utility"]
classifiers = [
    # Python Metadata
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    # Project Metadata
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Developers",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
