
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-02T11:52:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7da0a1a44b1c41e964d0d5ae4e173c33f4940fc0",
 "version": "0.5.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
