
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-08T02:38:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ec52a427b73b700d67b5c4c6fcd2894ea24fbab",
 "version": "0.4.dev2219"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
