
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-05T16:44:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6b13c8ecd0dc7aab307cf89534c5a3c61a2093a",
 "version": "v0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
